version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: autos
      MYSQL_PASSWORD: autos2024
      MYSQL_DATABASE: autos_db

  app:
    build:
      context: ./gpds-autos
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql-db:3306/autos_db
      spring.datasource.username: autos
      spring.datasource.password: autos2024
      spring.jpa.hibernate.ddl-auto: create
    depends_on:
      - mysql-db

